apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: onetimesecret

resources:
- ../../base

images:
- name: redis
  newTag: "7.2-alpine"

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: redis
  path: deployment-patch.yaml
- target:
    version: v1
    kind: PersistentVolumeClaim
    name: onetimesecret-db-pvc
  path: pvc-patch.yaml
