apiVersion: v1
kind: Service
metadata:
  name: onetimesecret
  labels:
    app: onetimesecret
    tier: frontend
  namespace: onetimesecret
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: onetimesecret
    tier: frontend
status:
  loadBalancer: {}