kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: onetimesecret-db-pvc
  namespace: onetimesecret
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  storageClassName: nfs-csi-k8s
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi