apiVersion: v2
name: onetimesecret
description: OneTimeSecret deployment using the upstream snappass chart
type: application
version: 0.1.0
appVersion: "2.1.2"

dependencies:
- name: snappass
  version: 0.4.3
  repository: https://lmacka.github.io/helm-snappass/
