snappass:
  ingress:
    enabled: true
    className: "nginx"
    hosts:
    - host: onetimesecret-k8s.silabs.net
      paths:
      - path: /
        pathType: Prefix

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 512Mi

  valkey:
    storage:
      className: nfs-csi-k8s
      requestedSize: 10Gi
