apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    tier: database
  namespace: onetimesecret
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
    tier: database
status:
  loadBalancer: {}