apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: onetimesecret-prod
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - srv: db
        path: onetimesecret/appsets/db/overlays/prod
      - srv: app
        path: onetimesecret/appsets/app/overlays/prod
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: onetimesecret-component
              operator: In
              values:
                - db
        - matchExpressions:
            - key: onetimesecret-component
              operator: In
              values:
                - app
  template:
    metadata:
      name: 'onetimesecret-{{srv}}'
      labels:
        onetimesecret-component: '{{srv}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: 'https://github.com/paobulas/argo-cd-apps'
        targetRevision: main
        path: '{{path}}'
      destination:
        name: in-cluster
        namespace: onetimesecret
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
        syncOptions:
          - CreateNamespace=true
