apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onetimesecret-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: onetimesecret/overlays/dev
    repoURL: https://github.com/paobulas/argo-cd-apps
    targetRevision: main
  destination:
    namespace: pricelist
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
